module.exports = {
  DASHBOARD_VIEW: 'DASHBOARD_VIEW',
  USERS_VIEW: 'USERS_VIEW',
  USERS_EDIT: 'USERS_EDIT',
  CONTACTS_VIEW: 'CONTACTS_VIEW',
  CONTACTS_REPLY: 'CONTACTS_REPLY',
  APP_ONLY: 'APP_ONLY'
};
